#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "john"
    args.site_name = "Moodle"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e74bc7a29a2e2216820cd348b642fc0b64b8c5b6.name = "Upgrade from 4.5.2~ynh1"
