; Additional php.ini defines, specific to this pool of workers.

php_value[max_input_vars] = __PHP_MAX_INPUT_VARS__
php_value[memory_limit] = __PHP_MEMORY_LIMIT__
php_value[max_execution_time] = __PHP_MAX_EXECUTION_TIME__
php_value[upload_max_filesize] = __PHP_UPLOAD_MAX_FILESIZE__
php_value[post_max_size] = __PHP_UPLOAD_MAX_FILESIZE__
