#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
# UPGRADE A CONFIGURATION
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

domain=${new_domain%/}
path=${new_path%/}
dir="__DIR__"

ynh_backup_if_checksum_is_different --file="$install_dir/config.php"

if [ "$new_path" == "/" ]; then
	ynh_add_config --template="../conf/config-domain.php" --destination="$install_dir/config.php"
else
	ynh_add_config --template="../conf/config-path.php" --destination="$install_dir/config.php"
fi

ynh_store_file_checksum --file="$install_dir/config.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
